// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5a5DL1gM5OTCTn1U9A9wkPMbmTeAlEII',
    appId: '1:58848976091:web:30fc52b9e1aef98ed140fe',
    messagingSenderId: '58848976091',
    projectId: 'crypto1390231732819',
    authDomain: 'crypto1390231732819.firebaseapp.com',
    storageBucket: 'crypto1390231732819.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPp14qrv8fRMtJ2JBJmPxmhh5LZ4sSuOc',
    appId: '1:58848976091:android:63ad3fc4823c21dcd140fe',
    messagingSenderId: '58848976091',
    projectId: 'crypto1390231732819',
    storageBucket: 'crypto1390231732819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVBeyaHyVfJu1bg6ZfkJ7uMaTf16yAgVg',
    appId: '1:58848976091:ios:c24579b41eb4d721d140fe',
    messagingSenderId: '58848976091',
    projectId: 'crypto1390231732819',
    storageBucket: 'crypto1390231732819.appspot.com',
    iosClientId: '58848976091-t7c6584om6s904jrit2f0algagkes2f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptowallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVBeyaHyVfJu1bg6ZfkJ7uMaTf16yAgVg',
    appId: '1:58848976091:ios:07b92054439654ebd140fe',
    messagingSenderId: '58848976091',
    projectId: 'crypto1390231732819',
    storageBucket: 'crypto1390231732819.appspot.com',
    iosClientId: '58848976091-jvrpdva3i03ocanpokpmsnod7mhvb4m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptowallet.RunnerTests',
  );
}
